name: Build ioscado IPA (iOS 17 Stable)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    # QUAY VỀ MACOS-14 (Chứa Xcode 15.4 - Tương thích tốt nhất iOS 17)
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Create global.json to Force .NET 8
      run: dotnet new globaljson --sdk-version 8.0.400 --roll-forward latestFeature
        
    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Publish App
      # SỬA CHỮA:
      # 1. Thêm -p:_SuppressSdkMismatch=true: Để ép .NET 8 chịu chạy trên Xcode 15.4 cũ hơn
      # 2. Thêm -p:SupportedOSPlatformVersion=15.0: Để đảm bảo chạy được từ iOS 15 đến iOS 17
      run: |
        dotnet publish ioscado/ioscado.csproj -f net8.0-ios -r ios-arm64 -c Release -p:ArchiveOnBuild=true -p:EnableCodeSigning=false -p:CodesignKey="-" -p:CheckEolTargetFramework=false -p:TargetFrameworks=net8.0-ios -p:PlatformTarget=arm64 -p:PublishTrimmed=false -p:MtouchLink=SdkOnly -p:_SuppressSdkMismatch=true -p:SupportedOSPlatformVersion=15.0
    
    - name: Create IPA
      run: |
        cd ioscado/bin/Release/net8.0-ios/ios-arm64/publish/
        
        mkdir Payload
        mv *.app Payload/
        zip -r ioscado.ipa Payload
        
        mv ioscado.ipa ../../../../../../

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ioscado-IPA
        path: ioscado.ipa
