name: Build ioscado IPA (Final Fix Xcode)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    # THAY ĐỔI 1: Nâng cấp lên macos-15 (Sequoia) để có Xcode 16 & iOS 18 SDK
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Create global.json to Force .NET 8
      run: dotnet new globaljson --sdk-version 8.0.400 --roll-forward latestFeature
        
    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Publish App
      # THAY ĐỔI 2: Thêm -p:PublishTrimmed=false và -p:MtouchLink=SdkOnly
      # Ý nghĩa: Tắt tính năng "cắt gọt" code quá mức (Trimmer) để tránh lỗi thiếu thư viện iOS 18
      run: |
        dotnet publish ioscado/ioscado.csproj -f net8.0-ios -r ios-arm64 -c Release -p:ArchiveOnBuild=true -p:EnableCodeSigning=false -p:CodesignKey="-" -p:CheckEolTargetFramework=false -p:TargetFrameworks=net8.0-ios -p:PlatformTarget=arm64 -p:PublishTrimmed=false -p:MtouchLink=SdkOnly
    
    - name: Create IPA
      run: |
        cd ioscado/bin/Release/net8.0-ios/ios-arm64/publish/
        
        mkdir Payload
        mv *.app Payload/
        zip -r ioscado.ipa Payload
        
        mv ioscado.ipa ../../../../../../

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ioscado-IPA
        path: ioscado.ipa
