name: Build ioscado IPA (Subfolder)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Install MAUI Workload
      run: dotnet workload install maui-ios

    - name: Publish App
      # Đã thêm tên thư mục ioscado/ vào trước
      run: |
        dotnet publish ioscado/ioscado.csproj -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:EnableCodeSigning=false -p:CodesignKey="-"
    
    - name: Create IPA
      run: |
        # Đã thêm ioscado/ vào đường dẫn
        cd ioscado/bin/Release/net8.0-ios/ios-arm64/publish/
        
        mkdir Payload
        mv *.app Payload/
        zip -r ioscado.ipa Payload
        # Di chuyển ra xa hơn 1 cấp
        mv ioscado.ipa ../../../../../../

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ioscado-IPA
        path: ioscado.ipa
