name: Build ioscado IPA (Force ARM64)

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Create global.json to Force .NET 8
      run: dotnet new globaljson --sdk-version 8.0.400 --roll-forward latestFeature
        
    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Publish App
      # SỬA CHỐT HẠ Ở ĐÂY: 
      # Thêm tham số: -p:PlatformTarget=arm64
      # Ý nghĩa: "Tao không cần biết mày mặc định là gì, bắt buộc phải build ra ARM64 cho tao!"
      run: |
        dotnet publish ioscado/ioscado.csproj -f net8.0-ios -r ios-arm64 -c Release -p:ArchiveOnBuild=true -p:EnableCodeSigning=false -p:CodesignKey="-" -p:CheckEolTargetFramework=false -p:TargetFrameworks=net8.0-ios -p:PlatformTarget=arm64
    
    - name: Create IPA
      run: |
        cd ioscado/bin/Release/net8.0-ios/ios-arm64/publish/
        
        mkdir Payload
        mv *.app Payload/
        zip -r ioscado.ipa Payload
        
        mv ioscado.ipa ../../../../../../

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ioscado-IPA
        path: ioscado.ipa
